import { TestData } from './data/TestData';
//import { ApiService } from './api/ApiService';
import { Test } from './types/types';
import './styles/main.css';
import { ControlPanel } from './components/controlPanel/ControlPanel';
import { Table } from './components/table/Table';
import { TableBody } from './components/table/TableBody';
import { Dialog } from './components/dialog/Dialog';

export class App {
  static app: App;
  private testData: TestData;

  public static getApp(): App {
    if (!App.app) {
      App.app = new App();
    }
    return App.app;
  }

  private constructor() {
    this.testData = new TestData([]);
    this.init();
  }

  private async init(): Promise<void> {
    const response: Test[] = [
      {
        case_id: 1,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-20',
        ticket_status: 'Pending',
        ticket_id: 'TKT-001',
        result_id: 1000,
      },
      {
        case_id: 2,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-09-20',
        ticket_status: 'Open',
        ticket_id: 'TKT-002',
        result_id: 1001,
      },
      {
        case_id: 3,
        test_name: 'Login Test',
        customer: 'Customer D',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-11-06',
        ticket_status: 'Open',
        ticket_id: 'TKT-003',
        result_id: 1002,
      },
      {
        case_id: 4,
        test_name: 'Load Test',
        customer: 'Customer D',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-10-04',
        ticket_status: 'Open',
        ticket_id: 'TKT-004',
        result_id: 1003,
      },
      {
        case_id: 5,
        test_name: 'API Integration',
        customer: 'Customer C',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-10-11',
        ticket_status: 'Closed',
        ticket_id: 'TKT-005',
        result_id: 1004,
      },
      {
        case_id: 6,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-09-24',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-006',
        result_id: 1005,
      },
      {
        case_id: 7,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-11-26',
        ticket_status: 'Pending',
        ticket_id: 'TKT-007',
        result_id: 1006,
      },
      {
        case_id: 8,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-10-10',
        ticket_status: 'Open',
        ticket_id: 'TKT-008',
        result_id: 1007,
      },
      {
        case_id: 9,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-10-14',
        ticket_status: 'Open',
        ticket_id: 'TKT-009',
        result_id: 1008,
      },
      {
        case_id: 10,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-10-23',
        ticket_status: 'Closed',
        ticket_id: 'TKT-010',
        result_id: 1009,
      },
      {
        case_id: 11,
        test_name: 'API Integration',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-11-18',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-011',
        result_id: 1010,
      },
      {
        case_id: 12,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-11-25',
        ticket_status: 'Open',
        ticket_id: 'TKT-012',
        result_id: 1011,
      },
      {
        case_id: 13,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'North',
        test_status: 'In Progress',
        last_new_failed: '2024-11-18',
        ticket_status: 'Open',
        ticket_id: 'TKT-013',
        result_id: 1012,
      },
      {
        case_id: 14,
        test_name: 'Login Test',
        customer: 'Customer B',
        branch: 'North',
        test_status: 'Passed',
        last_new_failed: '2024-09-14',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-014',
        result_id: 1013,
      },
      {
        case_id: 15,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-11-23',
        ticket_status: 'Pending',
        ticket_id: 'TKT-015',
        result_id: 1014,
      },
      {
        case_id: 16,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'Main',
        test_status: 'Passed',
        last_new_failed: '2024-10-02',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-016',
        result_id: 1015,
      },
      {
        case_id: 17,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-11-28',
        ticket_status: 'Closed',
        ticket_id: 'TKT-017',
        result_id: 1016,
      },
      {
        case_id: 18,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-10-27',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-018',
        result_id: 1017,
      },
      {
        case_id: 19,
        test_name: 'Login Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-09-09',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-019',
        result_id: 1018,
      },
      {
        case_id: 20,
        test_name: 'Load Test',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'Passed',
        last_new_failed: '2024-11-01',
        ticket_status: 'Closed',
        ticket_id: 'TKT-020',
        result_id: 1019,
      },
      {
        case_id: 21,
        test_name: 'Load Test',
        customer: 'Customer B',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-10-28',
        ticket_status: 'Open',
        ticket_id: 'TKT-021',
        result_id: 1020,
      },
      {
        case_id: 22,
        test_name: 'UI Validation',
        customer: 'Customer B',
        branch: 'North',
        test_status: 'In Progress',
        last_new_failed: '2024-09-28',
        ticket_status: 'Pending',
        ticket_id: 'TKT-022',
        result_id: 1021,
      },
      {
        case_id: 23,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'South',
        test_status: 'In Progress',
        last_new_failed: '2024-09-26',
        ticket_status: 'Closed',
        ticket_id: 'TKT-023',
        result_id: 1022,
      },
      {
        case_id: 24,
        test_name: 'UI Validation',
        customer: 'Customer B',
        branch: 'East',
        test_status: 'Passed',
        last_new_failed: '2024-10-18',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-024',
        result_id: 1023,
      },
      {
        case_id: 25,
        test_name: 'Load Test',
        customer: 'Customer B',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-10-25',
        ticket_status: 'Open',
        ticket_id: 'TKT-025',
        result_id: 1024,
      },
      {
        case_id: 26,
        test_name: 'UI Validation',
        customer: 'Customer D',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-10-02',
        ticket_status: 'Open',
        ticket_id: 'TKT-026',
        result_id: 1025,
      },
      {
        case_id: 27,
        test_name: 'Login Test',
        customer: 'Customer A',
        branch: 'South',
        test_status: 'In Progress',
        last_new_failed: '2024-10-21',
        ticket_status: 'Pending',
        ticket_id: 'TKT-027',
        result_id: 1026,
      },
      {
        case_id: 28,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-11-06',
        ticket_status: 'Open',
        ticket_id: 'TKT-028',
        result_id: 1027,
      },
      {
        case_id: 29,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-11-10',
        ticket_status: 'Closed',
        ticket_id: 'TKT-029',
        result_id: 1028,
      },
      {
        case_id: 30,
        test_name: 'Login Test',
        customer: 'Customer C',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-10-25',
        ticket_status: 'Closed',
        ticket_id: 'TKT-030',
        result_id: 1029,
      },
      {
        case_id: 31,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-11-14',
        ticket_status: 'Open',
        ticket_id: 'TKT-031',
        result_id: 1030,
      },
      {
        case_id: 32,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-09-28',
        ticket_status: 'Closed',
        ticket_id: 'TKT-032',
        result_id: 1031,
      },
      {
        case_id: 33,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-02',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-033',
        result_id: 1032,
      },
      {
        case_id: 34,
        test_name: 'UI Validation',
        customer: 'Customer D',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-11-04',
        ticket_status: 'Closed',
        ticket_id: 'TKT-034',
        result_id: 1033,
      },
      {
        case_id: 35,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'North',
        test_status: 'Passed',
        last_new_failed: '2024-10-02',
        ticket_status: 'Pending',
        ticket_id: 'TKT-035',
        result_id: 1034,
      },
      {
        case_id: 36,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-11-11',
        ticket_status: 'Pending',
        ticket_id: 'TKT-036',
        result_id: 1035,
      },
      {
        case_id: 37,
        test_name: 'Load Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-09-11',
        ticket_status: 'Open',
        ticket_id: 'TKT-037',
        result_id: 1036,
      },
      {
        case_id: 38,
        test_name: 'Signup Test',
        customer: 'Customer D',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-10-24',
        ticket_status: 'Open',
        ticket_id: 'TKT-038',
        result_id: 1037,
      },
      {
        case_id: 39,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Passed',
        last_new_failed: '2024-09-13',
        ticket_status: 'Pending',
        ticket_id: 'TKT-039',
        result_id: 1038,
      },
      {
        case_id: 40,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'South',
        test_status: 'In Progress',
        last_new_failed: '2024-09-27',
        ticket_status: 'Pending',
        ticket_id: 'TKT-040',
        result_id: 1039,
      },
      {
        case_id: 41,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-09-11',
        ticket_status: 'Open',
        ticket_id: 'TKT-041',
        result_id: 1040,
      },
      {
        case_id: 42,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-10-26',
        ticket_status: 'Open',
        ticket_id: 'TKT-042',
        result_id: 1041,
      },
      {
        case_id: 43,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-09-23',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-043',
        result_id: 1042,
      },
      {
        case_id: 44,
        test_name: 'Login Test',
        customer: 'Customer A',
        branch: 'South',
        test_status: 'In Progress',
        last_new_failed: '2024-11-15',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-044',
        result_id: 1043,
      },
      {
        case_id: 45,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-11-04',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-045',
        result_id: 1044,
      },
      {
        case_id: 46,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-10-08',
        ticket_status: 'Closed',
        ticket_id: 'TKT-046',
        result_id: 1045,
      },
      {
        case_id: 47,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-11-11',
        ticket_status: 'Open',
        ticket_id: 'TKT-047',
        result_id: 1046,
      },
      {
        case_id: 48,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'East',
        test_status: 'Passed',
        last_new_failed: '2024-09-16',
        ticket_status: 'Closed',
        ticket_id: 'TKT-048',
        result_id: 1047,
      },
      {
        case_id: 49,
        test_name: 'Login Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-12',
        ticket_status: 'Pending',
        ticket_id: 'TKT-049',
        result_id: 1048,
      },
      {
        case_id: 50,
        test_name: 'Login Test',
        customer: 'Customer E',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-10-24',
        ticket_status: 'Pending',
        ticket_id: 'TKT-050',
        result_id: 1049,
      },
      {
        case_id: 51,
        test_name: 'API Integration',
        customer: 'Customer C',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-10-24',
        ticket_status: 'Closed',
        ticket_id: 'TKT-051',
        result_id: 1050,
      },
      {
        case_id: 52,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'South',
        test_status: 'Passed',
        last_new_failed: '2024-11-15',
        ticket_status: 'Open',
        ticket_id: 'TKT-052',
        result_id: 1051,
      },
      {
        case_id: 53,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-11-04',
        ticket_status: 'Open',
        ticket_id: 'TKT-053',
        result_id: 1052,
      },
      {
        case_id: 54,
        test_name: 'Signup Test',
        customer: 'Customer D',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-09-22',
        ticket_status: 'Closed',
        ticket_id: 'TKT-054',
        result_id: 1053,
      },
      {
        case_id: 55,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-09-04',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-055',
        result_id: 1054,
      },
      {
        case_id: 56,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-11-10',
        ticket_status: 'Closed',
        ticket_id: 'TKT-056',
        result_id: 1055,
      },
      {
        case_id: 57,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'Main',
        test_status: 'Passed',
        last_new_failed: '2024-09-27',
        ticket_status: 'Pending',
        ticket_id: 'TKT-057',
        result_id: 1056,
      },
      {
        case_id: 58,
        test_name: 'UI Validation',
        customer: 'Customer B',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-09-18',
        ticket_status: 'Open',
        ticket_id: 'TKT-058',
        result_id: 1057,
      },
      {
        case_id: 59,
        test_name: 'UI Validation',
        customer: 'Customer B',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-10-24',
        ticket_status: 'Pending',
        ticket_id: 'TKT-059',
        result_id: 1058,
      },
      {
        case_id: 60,
        test_name: 'Login Test',
        customer: 'Customer B',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-11-21',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-060',
        result_id: 1059,
      },
      {
        case_id: 61,
        test_name: 'Load Test',
        customer: 'Customer D',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-23',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-061',
        result_id: 1060,
      },
      {
        case_id: 62,
        test_name: 'Login Test',
        customer: 'Customer A',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-11-14',
        ticket_status: 'Pending',
        ticket_id: 'TKT-062',
        result_id: 1061,
      },
      {
        case_id: 63,
        test_name: 'Load Test',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'Passed',
        last_new_failed: '2024-09-06',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-063',
        result_id: 1062,
      },
      {
        case_id: 64,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-26',
        ticket_status: 'Open',
        ticket_id: 'TKT-064',
        result_id: 1063,
      },
      {
        case_id: 65,
        test_name: 'UI Validation',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-11-09',
        ticket_status: 'Open',
        ticket_id: 'TKT-065',
        result_id: 1064,
      },
      {
        case_id: 66,
        test_name: 'Login Test',
        customer: 'Customer D',
        branch: 'North',
        test_status: 'Passed',
        last_new_failed: '2024-09-25',
        ticket_status: 'Pending',
        ticket_id: 'TKT-066',
        result_id: 1065,
      },
      {
        case_id: 67,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-11-23',
        ticket_status: 'Open',
        ticket_id: 'TKT-067',
        result_id: 1066,
      },
      {
        case_id: 68,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-10-01',
        ticket_status: 'Pending',
        ticket_id: 'TKT-068',
        result_id: 1067,
      },
      {
        case_id: 69,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-09-20',
        ticket_status: 'Pending',
        ticket_id: 'TKT-069',
        result_id: 1068,
      },
      {
        case_id: 70,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-11-18',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-070',
        result_id: 1069,
      },
      {
        case_id: 71,
        test_name: 'UI Validation',
        customer: 'Customer D',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-10-22',
        ticket_status: 'Pending',
        ticket_id: 'TKT-071',
        result_id: 1070,
      },
      {
        case_id: 72,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-12-02',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-072',
        result_id: 1071,
      },
      {
        case_id: 73,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'Main',
        test_status: 'Passed',
        last_new_failed: '2024-09-24',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-073',
        result_id: 1072,
      },
      {
        case_id: 74,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-10-16',
        ticket_status: 'Closed',
        ticket_id: 'TKT-074',
        result_id: 1073,
      },
      {
        case_id: 75,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'North',
        test_status: 'In Progress',
        last_new_failed: '2024-11-29',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-075',
        result_id: 1074,
      },
      {
        case_id: 76,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-09-13',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-076',
        result_id: 1075,
      },
      {
        case_id: 77,
        test_name: 'API Integration',
        customer: 'Customer B',
        branch: 'South',
        test_status: 'Failed',
        last_new_failed: '2024-11-04',
        ticket_status: 'Pending',
        ticket_id: 'TKT-077',
        result_id: 1076,
      },
      {
        case_id: 78,
        test_name: 'Signup Test',
        customer: 'Customer B',
        branch: 'North',
        test_status: 'In Progress',
        last_new_failed: '2024-11-08',
        ticket_status: 'Pending',
        ticket_id: 'TKT-078',
        result_id: 1077,
      },
      {
        case_id: 79,
        test_name: 'Signup Test',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'Passed',
        last_new_failed: '2024-11-07',
        ticket_status: 'Closed',
        ticket_id: 'TKT-079',
        result_id: 1078,
      },
      {
        case_id: 80,
        test_name: 'Login Test',
        customer: 'Customer D',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-10-24',
        ticket_status: 'Pending',
        ticket_id: 'TKT-080',
        result_id: 1079,
      },
      {
        case_id: 81,
        test_name: 'Signup Test',
        customer: 'Customer D',
        branch: 'East',
        test_status: 'Passed',
        last_new_failed: '2024-10-13',
        ticket_status: 'Pending',
        ticket_id: 'TKT-081',
        result_id: 1080,
      },
      {
        case_id: 82,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-10-18',
        ticket_status: 'Closed',
        ticket_id: 'TKT-082',
        result_id: 1081,
      },
      {
        case_id: 83,
        test_name: 'Load Test',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'Failed',
        last_new_failed: '2024-11-07',
        ticket_status: 'Closed',
        ticket_id: 'TKT-083',
        result_id: 1082,
      },
      {
        case_id: 84,
        test_name: 'UI Validation',
        customer: 'Customer C',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-11-14',
        ticket_status: 'Open',
        ticket_id: 'TKT-084',
        result_id: 1083,
      },
      {
        case_id: 85,
        test_name: 'API Integration',
        customer: 'Customer C',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-11-02',
        ticket_status: 'Open',
        ticket_id: 'TKT-085',
        result_id: 1084,
      },
      {
        case_id: 86,
        test_name: 'Load Test',
        customer: 'Customer B',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-10-02',
        ticket_status: 'Closed',
        ticket_id: 'TKT-086',
        result_id: 1085,
      },
      {
        case_id: 87,
        test_name: 'API Integration',
        customer: 'Customer E',
        branch: 'West',
        test_status: 'In Progress',
        last_new_failed: '2024-09-24',
        ticket_status: 'Pending',
        ticket_id: 'TKT-087',
        result_id: 1086,
      },
      {
        case_id: 88,
        test_name: 'Load Test',
        customer: 'Customer A',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-09-30',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-088',
        result_id: 1087,
      },
      {
        case_id: 89,
        test_name: 'Load Test',
        customer: 'Customer D',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-11-21',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-089',
        result_id: 1088,
      },
      {
        case_id: 90,
        test_name: 'UI Validation',
        customer: 'Customer B',
        branch: 'West',
        test_status: 'Passed',
        last_new_failed: '2024-10-27',
        ticket_status: 'Pending',
        ticket_id: 'TKT-090',
        result_id: 1089,
      },
      {
        case_id: 91,
        test_name: 'Load Test',
        customer: 'Customer B',
        branch: 'South',
        test_status: 'Passed',
        last_new_failed: '2024-09-28',
        ticket_status: 'Open',
        ticket_id: 'TKT-091',
        result_id: 1090,
      },
      {
        case_id: 92,
        test_name: 'API Integration',
        customer: 'Customer D',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-09-12',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-092',
        result_id: 1091,
      },
      {
        case_id: 93,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'Main',
        test_status: 'Failed',
        last_new_failed: '2024-11-08',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-093',
        result_id: 1092,
      },
      {
        case_id: 94,
        test_name: 'Signup Test',
        customer: 'Customer E',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-09-05',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-094',
        result_id: 1093,
      },
      {
        case_id: 95,
        test_name: 'API Integration',
        customer: 'Customer A',
        branch: 'North',
        test_status: 'Failed',
        last_new_failed: '2024-10-20',
        ticket_status: 'Pending',
        ticket_id: 'TKT-095',
        result_id: 1094,
      },
      {
        case_id: 96,
        test_name: 'Login Test',
        customer: 'Customer C',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-11-07',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-096',
        result_id: 1095,
      },
      {
        case_id: 97,
        test_name: 'Signup Test',
        customer: 'Customer A',
        branch: 'West',
        test_status: 'Failed',
        last_new_failed: '2024-11-08',
        ticket_status: 'Closed',
        ticket_id: 'TKT-097',
        result_id: 1096,
      },
      {
        case_id: 98,
        test_name: 'UI Validation',
        customer: 'Customer E',
        branch: 'South',
        test_status: 'Passed',
        last_new_failed: '2024-09-15',
        ticket_status: 'Closed',
        ticket_id: 'TKT-098',
        result_id: 1097,
      },
      {
        case_id: 99,
        test_name: 'UI Validation',
        customer: 'Customer A',
        branch: 'Main',
        test_status: 'In Progress',
        last_new_failed: '2024-10-31',
        ticket_status: 'Pending',
        ticket_id: 'TKT-099',
        result_id: 1098,
      },
      {
        case_id: 100,
        test_name: 'Load Test',
        customer: 'Customer D',
        branch: 'East',
        test_status: 'In Progress',
        last_new_failed: '2024-11-12',
        ticket_status: 'Resolved',
        ticket_id: 'TKT-100',
        result_id: 1099,
      },
    ];
    this.testData = new TestData(response);
    this.addAppLogic(this.testData);
    // const apiService = new ApiService();

    /* try {
      const response: Test[] = await apiService.getTests();
      this.testData = new TestData(response);
      this.addAppLogic(this.testData);
    } catch (error) {
      console.error('Error:', error);
    } */
  }

  private addAppLogic(testData: TestData): void {
    new ControlPanel(testData);
    new Dialog(testData);
    new Table(testData);
  }

  public async refresh(): Promise<void> {
    const tableBody = document.querySelector('.table__table-body') as HTMLTableSectionElement;
    tableBody.innerHTML = '';

    new TableBody(this.testData);
  }
}
