import { ControlPanel } from './components/ControlPanel';
import { Table } from './components/Table';
import { Dialog } from './components/Dialog';
import { Footer } from './components/Footer';
import { Header } from './components/Header';
import { TestData } from './data/TestData';
import { ApiService } from './api/ApiService';
import { Test } from './types/types';
import './styles/main.css';

export class App {
  constructor() {
    this.initialize();
  }
  private async initialize() {
    const apiService = new ApiService();
    try {
      //const response: Test[] = await apiService.getTests();
      const response: Test[] = [
        {
          case_id: 725606635,
          test_name: 'Test_Alpha_Calculation311',
          customer: 'xddCompany',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 463415028,
        },
        {
          case_id: 129502424,
          test_name: 'Test_Delta_Calculation506',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK4211',
          result_id: 253437751,
        },
        {
          case_id: 176455471,
          test_name: 'Test_Beta_Calculation296',
          customer: 'xyzCorp',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK3551',
          result_id: 960247556,
        },
        {
          case_id: 606333313,
          test_name: 'Test_Gamma_Calculation356',
          customer: 'xyzCorp',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK6770',
          result_id: 430224227,
        },
        {
          case_id: 533861274,
          test_name: 'Test_Alpha_Calculation121',
          customer: 'testInc',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK6072',
          result_id: 325811782,
        },
        {
          case_id: 705172086,
          test_name: 'Test_Alpha_Calculation971',
          customer: 'mockLtd',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 230002932,
        },
        {
          case_id: 861382347,
          test_name: 'Test_Gamma_Calculation825',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 850600451,
        },
        {
          case_id: 399047762,
          test_name: 'Test_Delta_Calculation956',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK4098',
          result_id: 178082523,
        },
        {
          case_id: 658420300,
          test_name: 'Test_Delta_Calculation985',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 190505847,
        },
        {
          case_id: 892828184,
          test_name: 'Test_Beta_Calculation196',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 900435134,
        },
        {
          case_id: 657079185,
          test_name: 'Test_Delta_Calculation510',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 822944025,
        },
        {
          case_id: 827721872,
          test_name: 'Test_Alpha_Calculation205',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 794236231,
        },
        {
          case_id: 835451582,
          test_name: 'Test_Gamma_Calculation236',
          customer: 'xddCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 713515743,
        },
        {
          case_id: 868849916,
          test_name: 'Test_Gamma_Calculation783',
          customer: 'abcCompany',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 952084420,
        },
        {
          case_id: 131615945,
          test_name: 'Test_Delta_Calculation538',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK2504',
          result_id: 150407379,
        },
        {
          case_id: 485086285,
          test_name: 'Test_Alpha_Calculation774',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK8028',
          result_id: 159673279,
        },
        {
          case_id: 196004674,
          test_name: 'Test_Alpha_Calculation453',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 273239241,
        },
        {
          case_id: 375662923,
          test_name: 'Test_Gamma_Calculation524',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 279688557,
        },
        {
          case_id: 196218702,
          test_name: 'Test_Delta_Calculation469',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK9659',
          result_id: 120606966,
        },
        {
          case_id: 614135546,
          test_name: 'Test_Delta_Calculation634',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK9080',
          result_id: 354803291,
        },
        {
          case_id: 882742579,
          test_name: 'Test_Beta_Calculation966',
          customer: 'testInc',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK2282',
          result_id: 881318913,
        },
        {
          case_id: 811626458,
          test_name: 'Test_Gamma_Calculation318',
          customer: 'xddCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 967675166,
        },
        {
          case_id: 867013617,
          test_name: 'Test_Gamma_Calculation293',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 938013566,
        },
        {
          case_id: 871290851,
          test_name: 'Test_Gamma_Calculation989',
          customer: 'mockLtd',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK2865',
          result_id: 410826582,
        },
        {
          case_id: 900448403,
          test_name: 'Test_Alpha_Calculation505',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK7607',
          result_id: 219249543,
        },
        {
          case_id: 681458719,
          test_name: 'Test_Gamma_Calculation844',
          customer: 'xyzCorp',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 792679657,
        },
        {
          case_id: 504782279,
          test_name: 'Test_Gamma_Calculation827',
          customer: 'testInc',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK9443',
          result_id: 529382031,
        },
        {
          case_id: 398503653,
          test_name: 'Test_Delta_Calculation969',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK2462',
          result_id: 941787212,
        },
        {
          case_id: 110761564,
          test_name: 'Test_Gamma_Calculation363',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK9072',
          result_id: 555449907,
        },
        {
          case_id: 796170309,
          test_name: 'Test_Gamma_Calculation532',
          customer: 'mockLtd',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK9565',
          result_id: 484116224,
        },
        {
          case_id: 847273248,
          test_name: 'Test_Beta_Calculation384',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK3434',
          result_id: 812375949,
        },
        {
          case_id: 259968987,
          test_name: 'Test_Gamma_Calculation855',
          customer: 'xddCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 259070378,
        },
        {
          case_id: 122627671,
          test_name: 'Test_Beta_Calculation688',
          customer: 'abcCompany',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK7771',
          result_id: 102483300,
        },
        {
          case_id: 539264752,
          test_name: 'Test_Delta_Calculation675',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 162561433,
        },
        {
          case_id: 836095002,
          test_name: 'Test_Delta_Calculation725',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK6161',
          result_id: 794088841,
        },
        {
          case_id: 975002831,
          test_name: 'Test_Gamma_Calculation419',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK9423',
          result_id: 688495297,
        },
        {
          case_id: 687998537,
          test_name: 'Test_Beta_Calculation902',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK9663',
          result_id: 254455002,
        },
        {
          case_id: 777820035,
          test_name: 'Test_Beta_Calculation732',
          customer: 'abcCompany',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK2520',
          result_id: 344656139,
        },
        {
          case_id: 682817532,
          test_name: 'Test_Alpha_Calculation569',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK5679',
          result_id: 555426232,
        },
        {
          case_id: 849053069,
          test_name: 'Test_Beta_Calculation357',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 916500422,
        },
        {
          case_id: 795317199,
          test_name: 'Test_Delta_Calculation199',
          customer: 'testInc',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK8893',
          result_id: 743836822,
        },
        {
          case_id: 121775003,
          test_name: 'Test_Alpha_Calculation675',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK4027',
          result_id: 409110030,
        },
        {
          case_id: 636710031,
          test_name: 'Test_Beta_Calculation613',
          customer: 'abcCompany',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 745293527,
        },
        {
          case_id: 640857169,
          test_name: 'Test_Gamma_Calculation788',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 826374141,
        },
        {
          case_id: 265856460,
          test_name: 'Test_Gamma_Calculation261',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK9172',
          result_id: 121200248,
        },
        {
          case_id: 912721082,
          test_name: 'Test_Alpha_Calculation939',
          customer: 'mockLtd',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 284729835,
        },
        {
          case_id: 863220145,
          test_name: 'Test_Delta_Calculation751',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK6832',
          result_id: 871116004,
        },
        {
          case_id: 721925768,
          test_name: 'Test_Gamma_Calculation577',
          customer: 'xyzCorp',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 749409873,
        },
        {
          case_id: 679144694,
          test_name: 'Test_Alpha_Calculation810',
          customer: 'abcCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 716657997,
        },
        {
          case_id: 337361147,
          test_name: 'Test_Gamma_Calculation873',
          customer: 'mockLtd',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 545794248,
        },
        {
          case_id: 729137238,
          test_name: 'Test_Gamma_Calculation227',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK5512',
          result_id: 248448388,
        },
        {
          case_id: 406772954,
          test_name: 'Test_Delta_Calculation758',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK3359',
          result_id: 614344226,
        },
        {
          case_id: 688638939,
          test_name: 'Test_Gamma_Calculation810',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK7604',
          result_id: 295450500,
        },
        {
          case_id: 692320204,
          test_name: 'Test_Gamma_Calculation985',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 477959923,
        },
        {
          case_id: 249528734,
          test_name: 'Test_Alpha_Calculation142',
          customer: 'xddCompany',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK2757',
          result_id: 456931271,
        },
        {
          case_id: 753031113,
          test_name: 'Test_Gamma_Calculation239',
          customer: 'testInc',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 178085653,
        },
        {
          case_id: 398177003,
          test_name: 'Test_Beta_Calculation829',
          customer: 'xyzCorp',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK9159',
          result_id: 865381569,
        },
        {
          case_id: 686153091,
          test_name: 'Test_Gamma_Calculation861',
          customer: 'xyzCorp',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 736341514,
        },
        {
          case_id: 332895234,
          test_name: 'Test_Gamma_Calculation296',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK4686',
          result_id: 522518916,
        },
        {
          case_id: 499938850,
          test_name: 'Test_Gamma_Calculation789',
          customer: 'abcCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK3593',
          result_id: 158893275,
        },
        {
          case_id: 850399110,
          test_name: 'Test_Alpha_Calculation648',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 694262355,
        },
        {
          case_id: 790442705,
          test_name: 'Test_Alpha_Calculation865',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK2773',
          result_id: 973803908,
        },
        {
          case_id: 551467119,
          test_name: 'Test_Gamma_Calculation166',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 561588376,
        },
        {
          case_id: 913638372,
          test_name: 'Test_Alpha_Calculation691',
          customer: 'xyzCorp',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: '',
          result_id: 368274453,
        },
        {
          case_id: 407706579,
          test_name: 'Test_Alpha_Calculation184',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Closed',
          ticket_id: 'TICK2223',
          result_id: 975897895,
        },
        {
          case_id: 153507338,
          test_name: 'Test_Gamma_Calculation339',
          customer: 'abcCompany',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK5046',
          result_id: 490451923,
        },
        {
          case_id: 946870135,
          test_name: 'Test_Delta_Calculation788',
          customer: 'xddCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK5867',
          result_id: 400806467,
        },
        {
          case_id: 542016027,
          test_name: 'Test_Gamma_Calculation247',
          customer: 'abcCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK9583',
          result_id: 263162130,
        },
        {
          case_id: 773005409,
          test_name: 'Test_Delta_Calculation543',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 197613875,
        },
        {
          case_id: 888742747,
          test_name: 'Test_Gamma_Calculation749',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK1791',
          result_id: 718845751,
        },
        {
          case_id: 503286843,
          test_name: 'Test_Alpha_Calculation711',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK5950',
          result_id: 676583913,
        },
        {
          case_id: 981070172,
          test_name: 'Test_Beta_Calculation155',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 805095832,
        },
        {
          case_id: 848987076,
          test_name: 'Test_Alpha_Calculation601',
          customer: 'mockLtd',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK6901',
          result_id: 256111457,
        },
        {
          case_id: 303790617,
          test_name: 'Test_Alpha_Calculation222',
          customer: 'xddCompany',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 200414965,
        },
        {
          case_id: 557032762,
          test_name: 'Test_Beta_Calculation673',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK3250',
          result_id: 413266158,
        },
        {
          case_id: 576354338,
          test_name: 'Test_Delta_Calculation498',
          customer: 'mockLtd',
          branch: 'PRODUCTION',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK1582',
          result_id: 222499970,
        },
        {
          case_id: 624978282,
          test_name: 'Test_Delta_Calculation172',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 847429838,
        },
        {
          case_id: 985437317,
          test_name: 'Test_Gamma_Calculation106',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK3186',
          result_id: 572595035,
        },
        {
          case_id: 205097048,
          test_name: 'Test_Alpha_Calculation755',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK1984',
          result_id: 813791978,
        },
        {
          case_id: 631603526,
          test_name: 'Test_Gamma_Calculation646',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Closed',
          ticket_id: 'TICK1271',
          result_id: 238117900,
        },
        {
          case_id: 846570929,
          test_name: 'Test_Alpha_Calculation938',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK5977',
          result_id: 291264381,
        },
        {
          case_id: 455521390,
          test_name: 'Test_Gamma_Calculation839',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'Closed',
          ticket_id: 'TICK5982',
          result_id: 613382120,
        },
        {
          case_id: 575436788,
          test_name: 'Test_Beta_Calculation472',
          customer: 'abcCompany',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK2922',
          result_id: 107826931,
        },
        {
          case_id: 287721913,
          test_name: 'Test_Gamma_Calculation987',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 453471404,
        },
        {
          case_id: 132144067,
          test_name: 'Test_Gamma_Calculation889',
          customer: 'abcCompany',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: 'In Progress',
          ticket_id: 'TICK8801',
          result_id: 154969065,
        },
        {
          case_id: 667950562,
          test_name: 'Test_Gamma_Calculation809',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 406375491,
        },
        {
          case_id: 690908209,
          test_name: 'Test_Alpha_Calculation611',
          customer: 'xddCompany',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: '',
          ticket_id: 'TICK8949',
          result_id: 860331456,
        },
        {
          case_id: 330472872,
          test_name: 'Test_Gamma_Calculation801',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 983826025,
        },
        {
          case_id: 318502826,
          test_name: 'Test_Alpha_Calculation915',
          customer: 'xddCompany',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK8090',
          result_id: 299991207,
        },
        {
          case_id: 864980227,
          test_name: 'Test_Gamma_Calculation160',
          customer: 'testInc',
          branch: 'MASTER',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 912795758,
        },
        {
          case_id: 180036409,
          test_name: 'Test_Alpha_Calculation665',
          customer: 'xyzCorp',
          branch: 'STAGING',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK2031',
          result_id: 472499291,
        },
        {
          case_id: 671353371,
          test_name: 'Test_Delta_Calculation855',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'FAILED',
          ticket_status: 'In Progress',
          ticket_id: '',
          result_id: 154598231,
        },
        {
          case_id: 192233127,
          test_name: 'Test_Gamma_Calculation997',
          customer: 'xddCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: 'TICK6758',
          result_id: 484566408,
        },
        {
          case_id: 448132462,
          test_name: 'Test_Delta_Calculation325',
          customer: 'abcCompany',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 851072749,
        },
        {
          case_id: 607766259,
          test_name: 'Test_Delta_Calculation349',
          customer: 'xyzCorp',
          branch: 'MASTER',
          test_status: 'FAILED',
          ticket_status: 'Open',
          ticket_id: 'TICK9265',
          result_id: 757089528,
        },
        {
          case_id: 440006500,
          test_name: 'Test_Delta_Calculation788',
          customer: 'mockLtd',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Closed',
          ticket_id: '',
          result_id: 774019791,
        },
        {
          case_id: 410333221,
          test_name: 'Test_Gamma_Calculation263',
          customer: 'xyzCorp',
          branch: 'PRODUCTION',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: 'TICK7267',
          result_id: 242070940,
        },
        {
          case_id: 756847600,
          test_name: 'Test_Gamma_Calculation343',
          customer: 'xyzCorp',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: '',
          result_id: 557301933,
        },
        {
          case_id: 390215076,
          test_name: 'Test_Gamma_Calculation505',
          customer: 'testInc',
          branch: 'STAGING',
          test_status: 'PASSED',
          ticket_status: 'Open',
          ticket_id: 'TICK3099',
          result_id: 862056661,
        },
        {
          case_id: 834987991,
          test_name: 'Test_Gamma_Calculation887',
          customer: 'mockLtd',
          branch: 'DEV',
          test_status: 'PASSED',
          ticket_status: '',
          ticket_id: '',
          result_id: 326499130,
        },
      ];

      const testData = new TestData(response);
      this.renderApp(testData);
    } catch (error) {
      console.error('Error:', error);
    }
  }

  private renderApp(testData: TestData): void {
    document.title = 'KTestTicketUpdater';
    const mainContainer = document.createElement('div');
    mainContainer.className = 'main-container';

    const headerContainer = document.createElement('div');
    const header = new Header();
    header.render(headerContainer);
    mainContainer.appendChild(headerContainer);

    const content = document.createElement('div');
    content.className = 'content';

    const controlPanel = new ControlPanel(testData);
    controlPanel.render(content);

    const dialogContainer = document.createElement('div');
    dialogContainer.className = 'dialog-container';
    const dialog = new Dialog(testData);
    dialog.render(dialogContainer);
    content.appendChild(dialogContainer);

    const tableContainer = document.createElement('div');
    tableContainer.className = 'table-container';
    const dataTable = new Table(testData);
    dataTable.render(tableContainer);
    content.appendChild(tableContainer);

    mainContainer.appendChild(content);

    const footerContainer = document.createElement('div');
    const footer = new Footer();
    footer.render(footerContainer);
    mainContainer.appendChild(footerContainer);

    document.body.appendChild(mainContainer);
  }
}
